USE [Kama.Mefa.Azmoon]
GO

IF EXISTS(SELECT 1 FROM sys.procedures WHERE [object_id] = OBJECT_ID('adm.spDeleteDivisionOfLabor'))
	DROP PROCEDURE adm.spDeleteDivisionOfLabor
GO

CREATE PROCEDURE adm.spDeleteDivisionOfLabor
	@AID UNIQUEIDENTIFIER,
	@ALog NVARCHAR(MAX)
WITH ENCRYPTION
AS
BEGIN
	SET NOCOUNT ON;
	SET XACT_ABORT ON;

	DECLARE @ID UNIQUEIDENTIFIER = @AID,
		    @Log NVARCHAR(MAX)

	IF @ID IS NULL
		RETURN -2 -- ‘‰«”Â ‰«„⁄ »— «” 

	BEGIN TRY
		BEGIN TRAN

			DELETE 
			FROM adm.DivisionOfLabor 
			WHERE  ID = @ID

			EXEC pbl.spAddLog @Log
		COMMIT
	END TRY
	BEGIN CATCH
		;THROW
	END CATCH
	
	RETURN @@ROWCOUNT
END